framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            App\Domain\SendForgotPasswordEmailCommand: async
            App\Domain\SendWelcomeEmailCommand: async
