services:
  php:
    build:
      context: .devops/docker/php
    volumes:
      - .:/srv
    networks:
      - cb

  consumer:
    depends_on:
      - php
    build:
      context: .devops/docker/php
    volumes:
      - .:/srv
    command: php -d memory_limit=-1 bin/console messenger:consume async
    networks:
      - cb

  web:
    depends_on:
      - php
    build:
      context: .devops/docker/nginx/symfony
    volumes:
      - ./public:/srv/public
    networks:
      - cb

  db:
    image: mariadb:10.3
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - cb

  mailbox:
    image: mailhog/mailhog
    networks:
      - cb

volumes:
  db_data:

networks:
  cb:
    
