parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\SmsNotifier:
        arguments:
            $sid: '%env(string:TWILIO_SID)%'
            $token: '%env(string:TWILIO_TOKEN)%'
            $from: '%env(string:TWILIO_FROM)%'

    App\DataFixtures\UserFixtures:
        arguments:
            $testPhoneNumber: '%env(string:TWILIO_TEST_PHONE)%'
    
    App\Controller\Auth\SecurityController:
        arguments:
            $domain: '%env(string:DOMAIN_NAME)%'

when@test:
    services:
        _defaults:
            autowire: true
            autoconfigure: true

        App\Service\Validator:
            public: true

        App\Repository\UserRepository:
            public: true
