name: Launch Docker
description: Launch Docker based on compose.yaml file

runs:
  using: composite
  steps:
    - name: Starting docker
      run: docker compose -f compose.yaml -f compose.tests.yaml up -d
      shell: bash
