name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  prod:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Code 
        uses: actions/checkout@v4

      - name: Deployment
        uses: ./.devops/workflows/deployment
