name: Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
permissions:
  contents: read

jobs:
  pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Build / Start
        uses: ./.devops/workflows/docker

      - name: Build Vendor
        uses: ./.devops/workflows/php/build

      - name: Linter
        uses: ./.devops/workflows/php/lint
